/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
// Object3DNode removed in @react-three/fiber v9

// N, E, S, W
export const DIRECTION_PARAMS = [
  { rotation: Math.PI, dx: 0.5, dy: 0.3, dz: 0.7 },
  { rotation: Math.PI / 2, dx: 0.3, dy: 0.3, dz: 0.5 },
  { rotation: 0, dx: 0.5, dy: 0.3, dz: 0.3 },
  { rotation: -Math.PI / 2, dx: 0.8, dy: 0.3, dz: 0.5 },
];

export default function Model(props: React.JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF("Robot3D.glb") as any;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.node_id52.geometry}
        position={[0, -0.26, 0.24]}
        scale={[0.03, 0.05, 0.05]}
      >
        <meshStandardMaterial 
          color="#606060"
          roughness={0.4} 
          metalness={0.6}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("Robot3D.glb");
