/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
// Object3DNode removed in @react-three/fiber v9

// N, E, S, W
export const DIRECTION_PARAMS = [
  { rotation: Math.PI, dx: 0.5, dy: 0.3, dz: 0.7 },
  { rotation: Math.PI / 2, dx: 0.3, dy: 0.3, dz: 0.5 },
  { rotation: 0, dx: 0.5, dy: 0.3, dz: 0.3 },
  { rotation: -Math.PI / 2, dx: 0.8, dy: 0.3, dz: 0.5 },
];

export default function Model(props: Object3DNode<any, any>) {
  const group = useRef();
  const { nodes, materials } = useGLTF("Robot3D.glb") as any;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.node_id52.geometry}
        material={materials["79"]}
        position={[0, -0.26, 0.24]}
        scale={[0.03, 0.05, 0.05]}
      />
    </group>
  );
}

useGLTF.preload("Robot3D.glb");
