/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Object3DNode } from "@react-three/fiber";
// N, E, S, W
export const DIRECTION_PARAMS = [
  { rotation: 3.5, dx: 0.4, dy: 0.3, dz: 0.9 },
  { rotation: Math.PI / 2, dx: 0.2, dy: 0.3, dz: 0.4 },
  { rotation: 0.5, dx: 0.5, dy: 0.3, dz: 0.2 },
  { rotation: -Math.PI / 2, dx: 1.0, dy: 0.3, dz: 0.6 },
];

export default function Model(props: Object3DNode<any, any>) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Troll3D.glb") as any;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.node_id43.geometry} material={materials["63"]} position={[0.01, -0.26, 0.27]} scale={0.4} />
    </group>
  );
}

useGLTF.preload("/Troll3D.glb");
